# Generated by Django 4.2 on 2024-03-28 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сategories',
            new_name='Categories',
        ),
    ]
